name: Release to NuGet
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup Nuget
        uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}

      - name: Build Package
        run: msbuild MaterialSurface.csproj /p:Configuration=Release
        working-directory: ./MaterialSurface

      - name: Package Nuget
        run: nuget pack MaterialSurface.csproj -Prop Configuration=Release -Version 1.1.4
        working-directory: ./MaterialSurface

      - name: Add Github source
        run: nuget source Add -Name "github" -Source "https://nuget.pkg.github.com/princ3od/index.json" -UserName princ3od -Password ${{ secrets.GH_KEY }}
        working-directory: ./MaterialSurface

      - name: Push to GitHub registry
        run: nuget push **/*.nupkg -Source "github" -ApiKey ${{ secrets.GH_KEY }} -SkipDuplicate
        working-directory: ./MaterialSurface

      - name: Push to Nuget registry
        run: nuget push **/*.nupkg -Source "https://api.nuget.org/v3/index.json" -ApiKey ${{ secrets.NUGET_API_KEY }} -NoSymbols -SkipDuplicate
        working-directory: ./MaterialSurface
