name: Release to NuGet
on:
  push:
    tags:        
      - '*' 

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup Nuget
        uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}

      - name: Build Package
        run: msbuild MaterialSurface.csproj /p:Configuration=Release
        working-directory: ./MaterialSurface

      - name: Package Nuget
        run: nuget pack MaterialSurface.csproj -Prop Configuration=Release -Version ${{ github.event.release.tag_name_without_v }}
        working-directory: ./MaterialSurface

      - name: Push to Nuget registry
        run: nuget push **/*.nupkg -Source "https://api.nuget.org/v3/index.json" -ApiKey ${{ secrets.NUGET_API_KEY }} -NoSymbols -SkipDuplicate
        working-directory: ./MaterialSurface
